Deploy_php_website:
   runs-on: ubuntu-latest
   needs: Stop_Service
   steps:
     - name: Deploy to Server
       uses: easingthemes/ssh-deploy@main
       env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           REMOTE_HOST: ${{ secrets.SSH_PROD_HOST }}
           REMOTE_USER: ${{ secrets.SSH_PROD_USERNAME }}
           TARGET: "/var/www/web"
