name: website deployment
on:
  push:
    branches:
      - master
jobs:  
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy website to example.com
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_PROD_HOST }}
          USERNAME: ${{ secrets.SSH_PROD_USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "./*"
          target: "/home/ubuntu/test"
          strip_components: 1
          script: |
            sudo cp /home/ubuntu/test /var/www
          

      
